before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
    main: ./cmd/sensord/main.go
    ldflags:
      - -s -w -X main.Version={{.Tag}} -X main.Commit={{.Commit}} -X main.BuildTime={{.Date}}

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true
