before:
  hooks:
    - go mod tidy

builds:
  - id: sensord
    env:
      - CGO_ENABLED=0
    main: ./cmd/sensord/main.go
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Tag}}
    goos:
      - linux
    goarch:
      - arm

archives:
  - name_template: "sensord-v{{ .Version }}"
    format: binary

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true
